version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: spring_mysql
    restart: 'always'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring
      MYSQL_USER: user
      MYSQL_PASSWORD: pass